### ISSUE TITLE
unicode is not supported?

### ISSUE THREAD

**Issue by luojc0517** [yhirose/go-peg#13]
```
var SYNTAX = `
MARKER          <-   ['>'|'<'|'='|'&'|'|'|'!'|'"'|'('|')'|'!' | '$' | '#' ]
IDENTIFIER      <-   < [a-z|A-Z]+ ('-' / '_' / [a-zA-Z0-9])* / (!MARKER [\u4e00-\u9fff|a-z|A-Z])(!MARKER [\u4e00-\u9fff|a-z|A-Z|0-9|'/'|'_'|'-'|'.'])* >
`
```

init with SYNTAX will return an error `3:22 syntax error`

**Comment by yhirose** [comment]
No, it doesn't.
https://github.com/yhirose/go-peg/blob/de25d6753cf19a2efc86e8be820de367b9fd5e20/parser.go#L80-L85

As mentioned in readme, go-peg is no longer maintained. Please consider to use cpp-peglib which supports more features like Unicode literal (`\u????`) and is tested fully.
