### ISSUE TITLE
Negative lookahead predicate.

### ISSUE THREAD

**Issue by Kyras** [yhirose/go-peg#4]
I would need to create predicate to match every symbol but newline symbol.
Something like [^\n]* in regex or negative lookahead operator !"\n"*.
Would that be possible ?

**Comment by yhirose** [comment]
@Kyras, we can use the negative lookahead operator.


```
# a.peg
START <- TEXT '\n'
TEXT <- (!'\n' .)*
```

```bash
$ peglint -ast -s $'hello' a.peg
1:6 syntax error

$ peglint -ast -s $'hello\n' a.peg
+ START
  - TEXT ("hello")
```

Hope it would be helpful.

**Comment by yhirose** [comment]
@Kyras, please let me know if the above solution doesn't work for you.
